# Generated by Django 5.1.3 on 2024-12-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='movie_options',
        ),
        migrations.AddField(
            model_name='event',
            name='movie_options',
            field=models.JSONField(default=list),
        ),
    ]
