# Generated by Django 5.1.3 on 2024-12-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options_remove_event_guests_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventParticipant',
        ),
    ]
